// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/[lang]/automobilkunstleder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/automobilkunstleder">> = Specific
  const handler = {} as typeof import("../../src/app/[lang]/automobilkunstleder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[lang]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/contact">> = Specific
  const handler = {} as typeof import("../../src/app/[lang]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[lang]/datenschutz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/datenschutz">> = Specific
  const handler = {} as typeof import("../../src/app/[lang]/datenschutz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[lang]/impressum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/impressum">> = Specific
  const handler = {} as typeof import("../../src/app/[lang]/impressum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[lang]/material-viewer/[category]/[materialId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/material-viewer/[category]/[materialId]">> = Specific
  const handler = {} as typeof import("../../src/app/[lang]/material-viewer/[category]/[materialId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[lang]/other/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/other">> = Specific
  const handler = {} as typeof import("../../src/app/[lang]/other/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[lang]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../src/app/[lang]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/automobilkunstleder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automobilkunstleder">> = Specific
  const handler = {} as typeof import("../../src/app/automobilkunstleder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/datenschutz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/datenschutz">> = Specific
  const handler = {} as typeof import("../../src/app/datenschutz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/impressum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/impressum">> = Specific
  const handler = {} as typeof import("../../src/app/impressum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/other/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/other">> = Specific
  const handler = {} as typeof import("../../src/app/other/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/[lang]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../src/app/[lang]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
